
package com.raven.form;

import Connection.DatabaseConnection;
import com.raven.main.Main;
import com.raven.table.CheckBoxTableHeaderRenderer;
import com.raven.table.TableCustom;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



public class Form_Diskon extends javax.swing.JPanel {
    String ID;
    private TableRowSorter<DefaultTableModel> sorter;
    public Form_Diskon() {
        initComponents();
        loadTable();
        TableCustom.apply(scroll, TableCustom.TableType.DEFAULT);
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        cmdDelete = new com.raven.swing.ButtonAction();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtSearch = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        cmdEdit = new com.raven.swing.ButtonAction();
        cmdNew = new com.raven.swing.ButtonAction();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(182, 234, 234));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        cmdDelete.setBackground(new java.awt.Color(255, 255, 255));
        cmdDelete.setText("Hapus");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        table.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECT", "#", "ID", "NAMA BARANG", "JUMLAH", "KETERANGAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scroll.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(1).setMaxWidth(30);
            table.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        lbTitle.setText("EMPLOYEE");

        cmdEdit.setBackground(new java.awt.Color(255, 255, 255));
        cmdEdit.setText("Edit");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });

        cmdNew.setBackground(new java.awt.Color(255, 255, 255));
        cmdNew.setText("Tambah");
        cmdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addContainerGap(981, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                    .addComponent(scroll))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Diskon");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    void loadTable() {
        DefaultTableModel tbl = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                if (column == 0) return Boolean.class; // Checkbox
                return super.getColumnClass(column);
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0; // Checkbox only editable
            }
        };

        tbl.addColumn("Select");
        tbl.addColumn("#");
        tbl.addColumn("ID");
        tbl.addColumn("Syarat Jumlah Diskon");
        tbl.addColumn("Jumlah Diskon");

        try {
            String query = "SELECT * FROM diskon";
            ResultSet rs = DatabaseConnection.getData(query);
            int no = 1;
            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("syarat_jumlah_diskon");
                String stok = rs.getString("jumlah_diskon");
                tbl.addRow(new Object[]{false, no++, id, nama, stok});
                
                table.getColumnModel().getColumn(0).setPreferredWidth(30);  // Checkbox
                table.getColumnModel().getColumn(1).setPreferredWidth(30);  // #
                table.getColumnModel().getColumn(2).setPreferredWidth(200); // ID
                table.getColumnModel().getColumn(3).setPreferredWidth(250); // Nama
                table.getColumnModel().getColumn(4).setPreferredWidth(200);  // Stok
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

        table.setModel(tbl);
        sorter = new TableRowSorter<>(tbl);
        table.setRowSorter(sorter);

        // Checkbox di header
        table.getColumnModel().getColumn(0).setHeaderRenderer(new CheckBoxTableHeaderRenderer(table, 0));
    
    }
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
       Main main = (Main) SwingUtilities.getWindowAncestor(this);

        JPanel glass = new JPanel();
        glass.setBackground(new Color(0, 0, 0, 150));
        glass.setOpaque(true);
        main.setGlassPane(glass);
        glass.setVisible(true);

        JDialog dialog = new JDialog(main, "Create Barang", true);
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(main);

        CreateDiskon createPanel = new CreateDiskon(this); // kirim panel utama ke panel popup
        dialog.getContentPane().add(createPanel);

        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                glass.setVisible(false);
            }

            @Override
            public void windowClosing(WindowEvent e) {
                glass.setVisible(false);
            }
        });


        int selectedRow = table.getSelectedRow();
        if (selectedRow != -1) {
            String selectedId = table.getValueAt(selectedRow, 2).toString();
            String nama = table.getValueAt(selectedRow, 3).toString();
            String harga = table.getValueAt(selectedRow, 4).toString();
            createPanel.setEditMode(true);
            createPanel.setSelectedId(selectedId);  
            createPanel.setSyarat(nama);
            createPanel.setJumlah(harga);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris untuk diedit!");
        }

        dialog.setVisible(true);
    }//GEN-LAST:event_cmdEditActionPerformed

    private void cmdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNewActionPerformed
        Main main = (Main) SwingUtilities.getWindowAncestor(this);

        JPanel glass = new JPanel();
        glass.setBackground(new Color(0, 0, 0, 150));
        glass.setOpaque(true);
        main.setGlassPane(glass);
        glass.setVisible(true);

        JDialog dialog = new JDialog(main, "Create Barang", true);
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(main);

        CreateDiskon createPanel = new CreateDiskon(this); // kirim panel utama ke panel popup
        dialog.getContentPane().add(createPanel);

        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                glass.setVisible(false);
            }

            @Override
            public void windowClosing(WindowEvent e) {
                glass.setVisible(false);
            }
        });

        dialog.setVisible(true);

    }//GEN-LAST:event_cmdNewActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
         if(table.getSelectedRow() != -1) {
            int result = JOptionPane.showConfirmDialog(null, "Yakin Ingin Mengapus Data Tersebut?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                String query = "DELETE FROM diskon WHERE id = ?";

                try (PreparedStatement ps = DatabaseConnection.getConn().prepareStatement(query)) {
                    ps.setInt(1, Integer.valueOf(table.getValueAt(table.getSelectedRow(), 2).toString()));
                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data Berhasil DiHapus");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error DELETE: " + e.getMessage());
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Baris Untuk Dihapus");
        }
        loadTable();

    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ButtonAction cmdDelete;
    private com.raven.swing.ButtonAction cmdEdit;
    private com.raven.swing.ButtonAction cmdNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
